import { Inter } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/shared/Navbar';
import Footer from '@/components/shared/Footer';
import NextThemeProvider from '@/providers/NextThemeProvider';
import TanstackQuearyProvider from '@/providers/TanstackQuearyProvider';
import ActiveProvider from '@/providers/ActiveProvider';

const inter = Inter({
  subsets: ['latin'],
  weight: ['400', '700'],
});

export const metadata = {
  title: 'Shawal Islam',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en' suppressHydrationWarning data-theme='light'>
      <head>
        <link rel='shortcut icon' href='/logo.png' type='image/x-icon' />
      </head>
      <body className={`${inter.className} antialiased dark:bg-black`}>
        <NextThemeProvider>
          <TanstackQuearyProvider>
            <ActiveProvider>
              <Navbar />
              {children}
              <Footer />
            </ActiveProvider>
          </TanstackQuearyProvider>
        </NextThemeProvider>
      </body>
    </html>
  );
}
